# Generated by Django 2.2.1 on 2019-05-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
