# Generated by Django 2.2.1 on 2019-05-23 15:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import events.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Regular'), (1, 'Discount'), (2, 'Premium'), (3, 'V.I.P'), (4, 'Family')], default=0)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_bought', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_bought', models.DateTimeField(default=datetime.datetime.now)),
                ('is_payed', models.BooleanField(default=False)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.EventSeat')),
                ('user', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_expired', models.DateTimeField(default=events.utils.now_plus_15_min)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.EventTicket')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(2, 'PayPal'), (1, 'Bank Transfer'), (0, 'Card')], default=0)),
                ('date_payed', models.DateTimeField(default=datetime.datetime.now)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.EventTicket')),
            ],
        ),
    ]
