# Generated by Django 2.2.1 on 2019-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(1, 'Bank Transfer'), (0, 'Card'), (2, 'PayPal')], default=0),
        ),
    ]
