# Generated by Django 2.2.1 on 2019-05-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190523_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Card'), (2, 'PayPal'), (1, 'Bank Transfer')], default=0),
        ),
    ]
