# Generated by Django 2.2.1 on 2019-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190528_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseat',
            name='type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Discount'), (2, 'Premium'), (3, 'V.I.P'), (4, 'Family')], default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Card'), (1, 'Bank Transfer'), (2, 'PayPal')], default=0),
        ),
    ]
