# Generated by Django 2.2.1 on 2019-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190529_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='price_bought',
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(2, 'PayPal'), (1, 'Bank Transfer'), (0, 'Card')], default=0),
        ),
    ]
