# Generated by Django 2.2.1 on 2019-05-29 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190529_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventSeat'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(1, 'Bank Transfer'), (0, 'Card'), (2, 'PayPal')], default=0),
        ),
    ]
