# Generated by Django 2.2.1 on 2019-05-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190529_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='is_in_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(2, 'PayPal'), (1, 'Bank Transfer'), (0, 'Card')], default=0),
        ),
    ]
