# Generated by Django 2.2.1 on 2019-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190530_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseat',
            name='type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Discount'), (2, 'Premium'), (3, 'V.I.P'), (4, 'Family')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(1, 'Bank Transfer'), (0, 'Card'), (2, 'PayPal')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='eventseat',
            unique_together={('type', 'event')},
        ),
    ]
